### ISSUE TITLE
txaws.tests.test_credentials.CredentialsTestCase.test_errors_are_valueerrors_for_backwards_compat

### ISSUE THREAD

**Issue by exarkun** [twisted/txaws#62]
If `~/.aws/credentials` exists and has no default profile, `txaws.tests.test_credentials.CredentialsTestCase.test_errors_are_valueerrors_for_backwards_compat` fails like this:

```
Traceback (most recent call last):
  File "/home/exarkun/Work/LeastAuthority/txaws/txaws/tests/test_credentials.py", line 36, in test_errors_are_valueerrors_for_backwards_compat
    AWSCredentials(environ={ENV_ACCESS_KEY: "foo"})
  File "/home/exarkun/Environments/txaws/local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 346, in __exit__
    self._expectedName, reason.getTraceback()),
twisted.trial.unittest.FailTest: txaws.exception.CredentialsNotFoundError raised instead of ValueError:
 Traceback (most recent call last):
  File "/home/exarkun/Environments/txaws/local/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 112, in _run
    utils.runWithWarningsSuppressed, self._getSuppress(), method)
  File "/home/exarkun/Environments/txaws/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/exarkun/Environments/txaws/local/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/exarkun/Work/LeastAuthority/txaws/txaws/tests/test_credentials.py", line 36, in test_errors_are_valueerrors_for_backwards_compat
    AWSCredentials(environ={ENV_ACCESS_KEY: "foo"})
--- <exception caught here> ---
  File "/home/exarkun/Work/LeastAuthority/txaws/txaws/tests/test_credentials.py", line 36, in test_errors_are_valueerrors_for_backwards_compat
    AWSCredentials(environ={ENV_ACCESS_KEY: "foo"})
  File "/home/exarkun/Work/LeastAuthority/txaws/txaws/credentials.py", line 51, in __init__
    _, secret_key = _load_shared_credentials(environ=environ)
  File "/home/exarkun/Work/LeastAuthority/txaws/txaws/credentials.py", line 81, in _load_shared_credentials
    raise CredentialsNotFoundError("No such profile {!r}".format(profile))
txaws.exception.CredentialsNotFoundError: No such profile 'default'
```

**Comment by exarkun** [comment]
Duplicate of #59
